CREATE TABLE IF NOT EXISTS saved_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    description VARCHAR(2000),
    url VARCHAR(1000) NOT NULL UNIQUE,
    image_url VARCHAR(1000),
    source_name VARCHAR(255),
    published_at VARCHAR(100),
    theme VARCHAR(50),
    saved_at TIMESTAMP NOT NULL
);
